<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Upload extends GC_Controller
{
	public function __construct()
	{
		parent::__construct();
	}

	public function up_logo_do()
	{
		return parent::up_logo_do(); // TODO: Change the autogenerated stub
	}

}
