<?php
/**
 * 线上支付类型通道固定金额配置
 * @说明：all 对应全部支付通道需要整数
 * @其他数字对应支付类型code值
 * @User: lqh
 * @Date: 2018/05/21
 * @Time: 10:41
 */
$config['isy'] = [
    'Yifu' => [4],
    'Ebei'=>[1,2],
    'Xinli'=> [5],
    'Yilian2'=>[2],
    'Yihui'=>[1,2],
    'Dida'  =>[1,2],
    'Lancan'=>[1,2],
    'Pay360'=>[1,2],
    'Amiss' => [4],
    'Amisw' => [5],
    'Debao' => [5],
    'Duobao' => [1,2],
    'Ehuifu' => [5],
    'Anquan' => [4],
    'Gaofutong'=>[1,2],
    'Hengrun'=>[1,2],
    'Yiwan' => [4,5],
    'Xinyu' => [4,5],
    'Tudou' => [8,12],
    'Jubaofu' => [1,4],
    'Gmifu' => [1,2,40],
    'Yirongtong' => [4,5],
    'Gmifut1' => [1,2,40],
    'Yi' => ['all'],
    'Kk' => ['all'],
    'Wufu' => ['all'],
    'Aima' => ['all'],
    'Bada' => ['all'],
    'Jifu' => ['all'],
    'Badu' => ['all'],
    'Gefu' => ['all'],
    'Yika' => ['all'],
    'Hefu' => ['all'],
    'Wufu' => ['all'],
    'Mayi' => ['all'],
    'Yida' => ['all'],
    'Anan' => ['all'],
    'Yunfu' => ['all'],
    'Xinfu' => ['all'],
    'Baiyi' => ['all'],
    'Xinfa' => ['all'],
    'Huifu' => ['all'],
    'Mobai' => ['all'],
    'Wanma' => ['all'],
    'Hongfu'=> ['all'],
    'Baiyi' => ['all'],
    'Okpay' => ['all'],
    'Suifu' => ['all'],
    'Yusan' => ['all'],
    'Baifu' => ['all'],
    'Likefu' => ['all'],
    'Hexing' => ['all'],
    'Huiyin' => ['all'],
    'Fengyi' => ['all'],
    'Maxpay' => ['all'],
    'Longfa' => ['all'],
    'Renxin' => ['all'],
    'Pay686' => ['all'],
    'Youjiu' => ['all'],
    'Yirong' => ['all'],
    'Qianfu' => ['all'],
    'Qixing' => ['all'],
    'Katong' => ['all'],
    'Sutong' => ['all'],
    'Tuojie' => ['all'],
    'Qingmu' => ['all'],
    'Yaopan' => ['all'],
    'Anyifu' => ['all'],
    'Tongyu' => ['all'],
    'Xunbao' => ['all'],
    'Qidian' => ['all'],
    'Tianfu' => ['all'],
    'Pay789' => ['all'],
    'Liying' => ['all'],
    'Feifan' => ['all'],
    'Miaofu' => ['all'],
    'Hexing' => ['all'],
    'Xinbao' => ['all'],
    'Lemei' => ['all'],
    'Easypay' => ['all'],
    'Suiyifu' => ['all'],
    'Lintong' => ['all'],
    'Wordfod' => ['all'],
    'Bofubao' => ['all'],
    'Tongsao' => ['all'],
    'Jishifu' => ['all'],
    'Baiqian' => ['all'],
    'Yiifut1' => ['all'],
    'Yiifut0' => ['all'],
    'Yunjian' => ['all'],
    'Yizhifu' => ['all'],
    'Yunrong' => ['all'],
    'Bangyin' => ['all'],
    'Quanshi' => ['all'],
    'Xinkong' => ['all'],
    'Gongniu' => ['all'],
    'Shengqian'=>['all'],
    'Tongbao' => ['all'],
    'Ziranfu' => ['all'],
    'Tongyin' => ['all'],
    'Yuntian' => ['all'],
    'Jinyifu' => ['all'],
    'Kaishuo' => ['all'],
    'Lewuxian' => ['all'],
    'Xibotong' => ['all'],
    'Caisheng' => ['all'],
    'Guangxin' => ['all'],
    'Yihuibao' => ['all'],
    'Tongxing' => ['all'],
    'Jiefuapi' => ['all'],
    'Xinlibao' => ['all'],
    'Shanyifu' => ['all'],
    'Baiqianfu' =>['all'],
    'Baisheng' => ['all'],
    'Qianying' => ['all'],
    'Tongdafu' => ['all'],
    'Zhongbao' => ['all'],
    'Zhifumao' => ['all'],
    'Huixiang' => ['all'],
    'Xinmeiti' => ['all'],
    'Yinshang' => ['all'],
    'Beifubao' => ['all'],
    'Mashanfu' => ['all'],
    'Gematong' => ['all'],
    'Hengtong' => ['all'],
    'Tianlong' => ['all'],
    'Hetongfu' => ['all'],
    'Quanqiufu' => ['all'],
    'Xiaoxiong' => ['all'],
    'Weifutong' => ['all'],
    'Guofutong' => ['all'],
    'Shunchang' => ['all'],
    'Zhenhaofu' => ['all'],
    'Kuairubao' => ['all'],
    'Shuanghui' => ['all'],
    'Huizheng' => ['all'],
    'Fenghuang' => ['all'],
    'Fuhuitong' => ['all'],
    'Yuebaoyun' => ['all'],
    'Mashangfu' => ['all'],
    'Yangguang' => ['all'],
    'Wanfutong' => ['all'],
    'Mingjiefu' => ['all'],
    'Aishangfu' => ['all'],
    'Shunyoufu' => ['all'],
    'Lintongbao' => ['all'],
    'Lelianmeng' => ['all'],
    'Xinganxian' => ['all'],
    'Zaixianbao' => ['all'],
    'Yunshouyin' => ['all'],
    'Yiliantong' => ['all'],
    'Zhugeliang' => ['all'],
    'Xiaomifeng' => ['all'],
    'Tongbaopay' => ['all'],
    'Guangfutong' => ['all'],
    'Shoukuanbao' => ['all'],
    'Shengfutong' => ['all'],
    'Changcheng05' => ['all'],
    'Ai' => ['all'],
    'Shanrubao' => ['all'],
    'Nangua' => ['all'],
    'Kuaifu' => ['all'],
    'Shouxin' => ['all'],
    'Shandian' => ['all'],
    'Kuaipay' => ['all'],
    'Huifeng' => ['all'],
    'Qianlaibao' => ['all'],
    'Zhihuibao' => ['all'],
];

/**
 * 线上支付类型通道使用原金额的支付通道
 * @说明：all 对应全部支付通道需要整数
 * @其他数字对应支付类型code值
 * @User: lqh
 * @Date: 2018/05/21
 * @Time: 10:41
 */
$config['isn'] = [
    'Mangguo' => ['all'],
    'Leizhisu' => ['all'],
    'Shangrubao' => ['all'],
    'Renrenqianbao' => ['all'],
    'Changfubao' => ['all'],
    'Fengxie' => ['all'],
    'WanmaPay' => ['all'],
    'Shanhu' => ['all'],
];
